app:
  name: demo
  model: test # debug / test / release by gin
  port: 8000

db:
  master:
    mysql: ${DB_USERNAME}:${DB_PASSWORD}@tcp(${DB_HOST}:${DB_POST})/${DB_NAME}?charset=utf8mb4&parseTime=True&loc=Local
    conn_max_lifetime: 2000
    max_open_conns: 100
    max_idle_conns: 5
    log_model: true

redis:
  client:
    addr: ${REDIS_HOST_PORT}
    password: ${REDIS_PASSWORD}
    db: ${REDIS_DB}
    pool: 5

log:
  log_path: ./logs/
  log_file_name: demo
  log_level: debug
  max_size: 1024
  max_backups: 3
  max_age: 7
  request_log: true
  stdout: false

jaeger:
  service_name: demo
  sampler_type: const # ratelimiting,const
  sampler_param: 0

pprof:
  open: false
  addr: :8001
